DROP DATABASE IF EXISTS EMPLOYEE_TRACKER;

CREATE DATABASE EMPLOYEE_TRACKER;

USE EMPLOYEE_TRACKER;

CREATE TABLE DEPARTMENTS (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100)
);
CREATE TABLE ROLES (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(100),
	SALARY INT
);
CREATE TABLE MANAGERS	(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(30),
	LAST_NAME VARCHAR(30)
);
CREATE TABLE EMPLOYEES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(30),
	LAST_NAME VARCHAR(30),
	DEPARTMENTS_ID INT,
	MANAGERS_ID INT,
	ROLES_ID INT,
	FOREIGN KEY (ROLES_ID) REFERENCES ROLES(ID),
	FOREIGN KEY (MANAGERS_ID) REFERENCES MANAGERS(ID)
); 

INSERT INTO DEPARTMENTS (NAME)
VALUES
    ("Accountz Payable"),
    ("Accountz Receevable"),
    ("R and Deez Nutz");

INSERT INTO MANAGERS (FIRST_NAME, LAST_NAME)
VALUES
    ("Scrooge", "McDuck"),
    ("Mr", "Burns");

INSERT INTO ROLES (TITLE, SALARY)
VALUES
    ("OfficeNinja", 1000),
    ("CharityCase", 2000),
    ("Scapegoat", 3000),
    ("BossSon", 4000);

INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, DEPARTMENTS_ID, MANAGERS_ID, ROLES_ID)
VALUES
    ("Djenya", "Countryman",1, 1, 1),
    ("Turlough", "Skewes", 2, 1, 2),
    ("Siofra", "Countryman", 3, 2, 3),
    ("Maxwell", "Skewes",3, 2, 4);