DROP DATABASE IF EXISTS EMPLOYEE_TRACKER;

CREATE DATABASE EMPLOYEE_TRACKER;

USE EMPLOYEE_TRACKER;

CREATE TABLE DEPARTMENT (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100)
);
CREATE TABLE ROLES (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(100),
	SALARY INT,
	DEPARTMENT_ID INT NOT NULL,
	CONSTRAINT fk_department FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);
CREATE TABLE EMPLOYEES (
	ID	INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(30),
	LAST_NAME VARCHAR(30),
	ROLE_ID	INT NOT NULL,
	MANAGER_ID INT NOT NULL,
	CONSTRAINT fk_role FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID),
	CONSTRAINT fk_manager FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)
); 