DROP DATABASE IF EXISTS EMPLOYEE_TRACKER;

CREATE DATABASE EMPLOYEE_TRACKER;

USE EMPLOYEE_TRACKER;

CREATE TABLE DEPARTMENTS (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100)
);
CREATE TABLE ROLES (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(100),
	SALARY INT,
	DEPARTMENTS_ID INT,
	CONSTRAINT fk_department FOREIGN KEY (DEPARTMENTS_ID) REFERENCES DEPARTMENTS(ID)
);
CREATE TABLE EMPLOYEES (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(30),
	LAST_NAME VARCHAR(30),
	ROLES_ID	INT,
	MANAGER_ID INT,
	CONSTRAINT fk_roles FOREIGN KEY (ROLES_ID) REFERENCES ROLES(ID) ON DELETE CASCADE,
	CONSTRAINT fk_manager FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(ID)
); 

INSERT INTO DEPARTMENTS (NAME)
VALUES
    ("Accountz Payable"),
    ("Accountz Receevable"),
    ("R and Deez Nutz");


INSERT INTO ROLES (TITLE, SALARY)
VALUES
    ("Office Ninja", 1000),
    ("CharityCase", 2000),
    ("Scapegoat", 3000),
    ("Boss Son", 4000);

INSERT INTO EMPLOYEES (FIRST_NAME, LAST_NAME, ROLES_ID)
VALUES
    ("Djenya", "Countryman", 1),
    ("Turlough", "Skewes", 2),
    ("Siofra", "Countryman", 3),
    ("Maxwell", "Skewes", 4);
